---
# install-cluster default vars

# This will be your bastion machine (if you run setup-bastion playbook)
assisted_installer_host: "{{ groups['bastion'][0] }}"
assisted_installer_port: 8090

# This will be your bastion machine (if you run setup-bastion playbook)
registry_host: "{{ groups['bastion'][0] }}"
registry_port: 5000

check_cluster_pause_seconds: 20

# Unmount virtual media on machines that report status as error in addition to "installing-pending-user-action"
unmount_virtual_media_on_error: true
