---
# Setups up hypervisors to host VMs
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud42.local ansible/hv-setup.yml
#

- name: Setup hypervisors to host VMs
  hosts: hv
  vars_files:
  - vars/lab.yml
  - vars/hv.yml
  pre_tasks:
  - ansible.builtin.fail:
      msg: "Hypervisors must be RHEL9"
    when: ansible_facts['distribution_major_version'] is version('9', '<')
  roles:
  - name: install-tc
    when: install_tc
  - hv-install
  - hv-network
  - role: hv-dnsmasq
    when: not setup_coredns
  - role: hv-coredns
    when: setup_coredns
  - hv-libvirt
  - role: hv-setup-disk2
    when: hostvars[inventory_hostname].disk2_enable | default(false) | bool
