---
# Create and deploy SNO cluster(s) with the Assisted Installer on IBMcloud
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/ibmcloud.local ansible/ibmcloud-sno-deploy.yml
#

- name: Create SNO cluster(s) with the assisted-installer on ibmcloud
  hosts: bastion
  vars_files:
  - vars/lab.yml
  - vars/ibmcloud.yml
  vars:
    assisted_installer_host: "{{ hostvars[inventory_hostname]['private_address'] }}"
    http_store_host: "{{ hostvars[inventory_hostname]['private_address'] }}"
    sno_use_lab_dhcp: false
    use_bastion_registry: false
  pre_tasks:
  - name: Validate deploying SNO
    fail:
      msg: "cluster_type is not 'sno'"
    when: cluster_type != "sno"
  roles:
  - validate-vars
  - ocp-release
  - create-ai-cluster
  - role: generate-discovery-iso
    vars:
      iso_name: "{{ groups['sno'][0] }}"
  - role: boot-iso
    vars:
      inventory_group: sno
      index: "1"
  - wait-hosts-discovered
  - configure-local-storage
  - install-cluster
  - sno-post-cluster-install
