---
# Create and deploy a cluster with the Assisted Installer on IBMcloud
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/ibmcloud.local ansible/ibmcloud-mno-deploy.yml
#

- name: Creates a multi node cluster with the assisted-installer on ibmcloud
  hosts: bastion
  vars_files:
  - vars/lab.yml
  - vars/ibmcloud.yml
  vars:
    assisted_installer_host: "{{ hostvars[inventory_hostname]['private_address'] }}"
    http_store_host: "{{ hostvars[inventory_hostname]['private_address'] }}"
    sno_use_lab_dhcp: false
    use_bastion_registry: false
  pre_tasks:
  - name: Validate deploying MNO
    fail:
      msg: "cluster_type is not 'mno'"
    when: cluster_type != "mno"
  roles:
  - validate-vars
  - ocp-release
  - create-ai-cluster
  - generate-discovery-iso
  - role: boot-iso
    vars:
      inventory_group: controlplane
      index: 3
  - role: boot-iso
    vars:
      inventory_group: worker
      index: "{{ worker_node_count }}"
  - wait-hosts-discovered
  - configure-local-storage
  - install-cluster
  - mno-post-cluster-install
