---
# MNO post-deploy add BMC to BareMetalHosts
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud42.local ansible/mno-post-deploy-add-bmc.yml
#

- name: MNO post-deploy add BMC to BareMetalHosts
  hosts: bastion
  vars_files:
  - vars/lab.yml
  - vars/all.yml
  roles:
  - validate-vars
  - mno-add-bmc
